//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 03:26:50 PM CDT 
//


package generated2;

import generated.MailingAddressType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MailingAddress" type="{}MailingAddressType"/>
 *         &lt;element name="PropertyAddress" type="{}PropertyAddressType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressesType", propOrder = {
    "mailingAddress",
    "propertyAddress"
})
public class AddressesType {

    @XmlElement(name = "MailingAddress", required = true)
    protected generated.MailingAddressType mailingAddress;
    @XmlElement(name = "PropertyAddress", required = true)
    protected PropertyAddressType propertyAddress;

    /**
     * Gets the value of the mailingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link generated.MailingAddressType }
     *     
     */
    public generated.MailingAddressType getMailingAddress() {
        return mailingAddress;
    }

    /**
     * Sets the value of the mailingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link generated.MailingAddressType }
     *     
     */
    public void setMailingAddress(MailingAddressType value) {
        this.mailingAddress = value;
    }

    /**
     * Gets the value of the propertyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyAddressType }
     *     
     */
    public PropertyAddressType getPropertyAddress() {
        return propertyAddress;
    }

    /**
     * Sets the value of the propertyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyAddressType }
     *     
     */
    public void setPropertyAddress(PropertyAddressType value) {
        this.propertyAddress = value;
    }

}
