//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.22 at 03:26:50 PM CDT 
//


package generated2;

import generated.AccountType;
import generated.AccountsType;
import generated.MailingAddressType;
import generated.MonthlyRentItemsType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MonthlyRentItems_QNAME = new QName("", "MonthlyRentItems");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link generated.MonthlyRentItemsType }
     * 
     */
    public generated.MonthlyRentItemsType createMonthlyRentItemsType() {
        return new generated.MonthlyRentItemsType();
    }

    /**
     * Create an instance of {@link generated.MailingAddressType }
     * 
     */
    public generated.MailingAddressType createMailingAddressType() {
        return new MailingAddressType();
    }

    /**
     * Create an instance of {@link AddressesType }
     * 
     */
    public AddressesType createAddressesType() {
        return new AddressesType();
    }

    /**
     * Create an instance of {@link PropertyAddressType }
     * 
     */
    public PropertyAddressType createPropertyAddressType() {
        return new PropertyAddressType();
    }

    /**
     * Create an instance of {@link generated.AccountsType }
     * 
     */
    public generated.AccountsType createAccountsType() {
        return new AccountsType();
    }

    /**
     * Create an instance of {@link generated.AccountType }
     * 
     */
    public generated.AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link generated.MonthlyRentItemsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MonthlyRentItems")
    public JAXBElement<generated.MonthlyRentItemsType> createMonthlyRentItems(generated.MonthlyRentItemsType value) {
        return new JAXBElement<generated.MonthlyRentItemsType>(_MonthlyRentItems_QNAME, MonthlyRentItemsType.class, null, value);
    }

}
